## Model Traning

In [140]:
# Basic Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# modeling
from sklearn.metrics import mean_squared_error , r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.metrics import r2_score , mean_absolute_error , mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [141]:
df = pd.read_csv(r'C:/Users/omtup/Downloads/StudentsPerformance (1).csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [142]:
print(f"categories feature of gender :{df['gender'].unique()}")
print(f"categories feature of lunch :{df['lunch'].unique()}")
print(f"categories feature of test preparation course :{df['test preparation course'].unique()}")
print(f'categories feature of race/ethnicity :{df['race/ethnicity'].unique()}')
print(f"categories feature of parental level of education :{df['parental level of education'].unique()}")
df.describe()

categories feature of gender :['female' 'male']
categories feature of lunch :['standard' 'free/reduced']
categories feature of test preparation course :['none' 'completed']
categories feature of race/ethnicity :['group B' 'group C' 'group A' 'group D' 'group E']
categories feature of parental level of education :["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [143]:
df.head(2)

X = df.drop(columns='math score' ,axis=1)
print(X.head())
y = df['math score']

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  reading score  writing score
0                    none             72             74
1               completed             90             88
2                    none             95             93
3                    none             57             44
4                    none             78             75

In [144]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude='object').columns
cat_features = X.select_dtypes(include='object').columns
from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer
numeric_transformer = StandardScaler()
# oh_transformer =  OneHotEncoder(drop='first' sparse_output=False).toarray()

preprocessor  = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer,cat_features),
        ("StandardScaler",numeric_transformer , num_features)
    ]
)

df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88

In [145]:
# gender_encoded  = oh_transformer.fit_transform(df[['gender']])
# df['gender_Encoded'] = gender_encoded[:, 0]
# print(df[['gender', 'gender_Encoded']])
print(df['gender'].unique())

['female' 'male']

In [146]:
from sklearn.model_selection import train_test_split
X_train , X_test ,y_train , y_test = train_test_split(X,y,test_size=0.2 , random_state=42)
X_train.shape , X_test.shape

((800, 7), (200, 7))